## Khasi - Sandbox

In [3]:
import import_ipynb
import clean_data
import pandas as pd
import modeling_2 as model
import feature_selection as fs
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.feature_selection import RFE

In [4]:
df = clean_data.runAll()

/Users/khasi-marc/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [3]:
df.head(20)

,AANAPII,ADM_RATE,AGEGE24,AGE_ENTRY,ANNHI,AVGFACSAL,C150_4_POOLED_SUPP,C150_L4_POOLED_SUPP,CCBASIC,CCSIZSET,...,OPENADMP_1.0,OPENADMP_2.0,OPENADMP_3.0,OPEFLAG_0.0,OPEFLAG_1.0,OPEFLAG_2.0,OPEFLAG_3.0,OPEFLAG_5.0,OPEFLAG_7.0,OPEFLAG_8.0
29624,0.0,0.445700,0.12,21.296296,0.0,4991.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29625,0.0,0.804900,0.26,22.980490,0.0,6734.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29626,0.0,0.682057,0.87,33.572347,0.0,3043.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29627,0.0,0.875600,0.27,23.485567,0.0,6257.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29628,0.0,0.504200,0.10,21.090276,0.0,5017.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29629,0.0,0.867000,0.11,21.283108,0.0,6551.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29630,0.0,0.682057,0.45,25.912446,0.0,4196.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29631,0.0,0.682057,0.56,28.943627,0.0,6157.0,0.505068,0.488505,11.996219,6.138233,...,0,0,1,1,0,0,0,0,0,0
29632,0.0,0.991700,0.29,23.637778,0.0,5708.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29633,0.0,0.776000,0.06,20.509892,0.0,7151.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29634,0.0,0.885200,0.02,19.702179,0.0,6111.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29635,0.0,0.682057,0.55,27.008856,0.0,4827.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29636,0.0,0.682057,0.48,28.438628,0.0,4598.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29637,0.0,1.000000,0.63,28.201923,0.0,3081.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29638,0.0,0.682057,0.47,26.362098,0.0,4701.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29639,0.0,0.682057,0.36,24.566388,0.0,4815.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29640,0.0,0.552400,0.64,28.573499,0.0,4254.0,0.505068,0.488505,11.996219,6.138233,...,0,1,0,1,0,0,0,0,0,0
29641,0.0,0.682057,0.50,26.793144,0.0,4750.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29642,0.0,0.682057,0.47,26.319912,0.0,4632.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0
29643,0.0,0.682057,0.44,26.483038,0.0,4464.0,0.505068,0.488505,11.996219,6.138233,...,1,0,0,1,0,0,0,0,0,0

In [38]:
list_of_buckets = ['DEG_SCIMATH', 
                   'DEG_TENG', 
                   'DEG_ART', 
                   'DEG_PROF', 
                   'DEG_HUM', 
                   'DEG_LAW', 
                   'DEG_MED', 
                   'DEG_MIL',
                   'DEG_BUS']

In [39]:
# returns all binary columns
ls_no_scale = [col for col in df if np.isin(df[col].unique(), [0, 1]).all()]

ls_no_scale.append('Year')
ls_no_scale.append('MD_EARN_WNE_P6')
df_scale = df.drop(ls_no_scale, axis=1)
df_no_scale = df[ls_no_scale]

In [40]:
df_scale.reset_index(inplace = True, drop = True)

In [41]:
df_no_scale.reset_index(inplace = True, drop = True)

In [42]:
df_scale.head()

,ADM_RATE,AGEGE24,AGE_ENTRY,AVGFACSAL,C150_4_POOLED_SUPP,C150_L4_POOLED_SUPP,CCBASIC,CCSIZSET,CCUGPROF,COSTT4_A,...,NPT4_75UP_,DEG_SCIMATH,DEG_TENG,DEG_ART,DEG_PROF,DEG_HUM,DEG_LAW,DEG_MED,DEG_MIL,DEG_BUS
0,0.445700,0.12,21.296296,4991.0,0.505068,0.488505,11.996219,6.138233,5.193526,24222.959714,...,0.0,0.1881,0.2191,0.0062,0.1323,0.2645,0.0,0.0000,0.0,0.1901
1,0.804900,0.26,22.980490,6734.0,0.505068,0.488505,11.996219,6.138233,5.193526,24222.959714,...,0.0,0.1702,0.0690,0.0414,0.0737,0.2761,0.0,0.1782,0.0,0.1913
2,0.682057,0.87,33.572347,3043.0,0.505068,0.488505,11.996219,6.138233,5.193526,24222.959714,...,0.0,0.0000,0.0000,0.0000,0.0000,1.0000,0.0,0.0000,0.0,0.0000
3,0.875600,0.27,23.485567,6257.0,0.505068,0.488505,11.996219,6.138233,5.193526,24222.959714,...,0.0,0.0905,0.2801,0.0372,0.0000,0.1375,0.0,0.1809,0.0,0.2739
4,0.504200,0.10,21.090276,5017.0,0.505068,0.488505,11.996219,6.138233,5.193526,24222.959714,...,0.0,0.0803,0.1311,0.0328,0.1327,0.4510,0.0,0.0410,0.0,0.1311

In [43]:
df_no_scale.head()

,AANAPII,ANNHI,CURROPER,DISTANCEONLY,HBCU,HSI,MENONLY,NANTI,PBI,TRIBAL,...,OPENADMP_3.0,OPEFLAG_0.0,OPEFLAG_1.0,OPEFLAG_2.0,OPEFLAG_3.0,OPEFLAG_5.0,OPEFLAG_7.0,OPEFLAG_8.0,Year,MD_EARN_WNE_P6
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,2003,28400.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,2003,34300.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,2003,29471.207226
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,2003,37400.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,2003,24000.000000

In [43]:
df_scale['C150_4_POOLED_SUPP'].describe()

count    3.385600e+04
mean     5.050678e-01
std      3.394002e-13
min      5.050678e-01
25%      5.050678e-01
50%      5.050678e-01
75%      5.050678e-01
max      5.050678e-01
Name: C150_4_POOLED_SUPP, dtype: float64

In [45]:
df_scale['C150_L4_POOLED_SUPP'].describe()

count    3.385600e+04
mean     4.885049e-01
std      4.081795e-13
min      4.885049e-01
25%      4.885049e-01
50%      4.885049e-01
75%      4.885049e-01
max      4.885049e-01
Name: C150_L4_POOLED_SUPP, dtype: float64

In [46]:
df_scale['CCBASIC'].describe()

count    3.385600e+04
mean     1.199622e+01
std      7.254748e-12
min      1.199622e+01
25%      1.199622e+01
50%      1.199622e+01
75%      1.199622e+01
max      1.199622e+01
Name: CCBASIC, dtype: float64

In [47]:
df_scale['CCSIZSET'].describe()

count    3.385600e+04
mean     6.138233e+00
std      2.267553e-12
min      6.138233e+00
25%      6.138233e+00
50%      6.138233e+00
75%      6.138233e+00
max      6.138233e+00
Name: CCSIZSET, dtype: float64

In [48]:
df_scale['CCUGPROF'].describe()

count    3.385600e+04
mean     5.193526e+00
std      2.814679e-12
min      5.193526e+00
25%      5.193526e+00
50%      5.193526e+00
75%      5.193526e+00
max      5.193526e+00
Name: CCUGPROF, dtype: float64

In [30]:
df_scale['RELAFFIL'].describe()

count    3.385600e+04
mean     5.439164e+01
std      2.257428e-11
min      5.439164e+01
25%      5.439164e+01
50%      5.439164e+01
75%      5.439164e+01
max      5.439164e+01
Name: RELAFFIL, dtype: float64

In [31]:
df_scale['UG'].describe()

count    3.385600e+04
mean     3.138752e+03
std      1.607101e-09
min      3.138752e+03
25%      3.138752e+03
50%      3.138752e+03
75%      3.138752e+03
max      3.138752e+03
Name: UG, dtype: float64

In [44]:
scale = StandardScaler()
scaled_arr = scale.fit_transform(df_scale)
scaled_df = pd.DataFrame(scaled_arr, columns = df_scale.columns)
scaled_df.head()

,ADM_RATE,AGEGE24,AGE_ENTRY,AVGFACSAL,C150_4_POOLED_SUPP,C150_L4_POOLED_SUPP,CCBASIC,CCSIZSET,CCUGPROF,COSTT4_A,...,NPT4_75UP_,DEG_SCIMATH,DEG_TENG,DEG_ART,DEG_PROF,DEG_HUM,DEG_LAW,DEG_MED,DEG_MIL,DEG_BUS
0,-1.686152,-2.467388,-1.123197,-0.580916,1.0,-1.0,0.0,1.0,0.0,0.038178,...,-0.760679,1.407189,1.308194,-0.270779,-0.358614,0.102681,-0.171099,-0.764770,-0.022196,0.460706
1,0.903349,-1.216280,-0.640738,0.389326,1.0,-1.0,0.0,1.0,0.0,0.038178,...,-0.760679,1.215642,0.041309,-0.015231,-0.542686,0.149952,-0.171099,-0.132693,-0.022196,0.469243
2,0.017765,4.234976,2.393439,-1.665272,1.0,-1.0,0.0,1.0,0.0,0.038178,...,-0.760679,-0.605656,-0.541070,-0.315790,-0.774191,3.099911,-0.171099,-0.764770,-0.022196,-0.891688
3,1.413031,-1.126915,-0.496052,0.123803,1.0,-1.0,0.0,1.0,0.0,0.038178,...,-0.760679,0.362778,1.823051,-0.045723,-0.774191,-0.414856,-0.171099,-0.123117,-0.022196,1.056870
4,-1.264421,-2.646118,-1.182215,-0.566444,1.0,-1.0,0.0,1.0,0.0,0.038178,...,-0.760679,0.253629,0.565450,-0.077666,-0.357357,0.862686,-0.171099,-0.619343,-0.022196,0.040973

In [45]:
complete_df = pd.concat([scaled_df, df_bin], axis = 1, sort = True)
complete_df.head()

,ADM_RATE,AGEGE24,AGE_ENTRY,AVGFACSAL,C150_4_POOLED_SUPP,C150_L4_POOLED_SUPP,CCBASIC,CCSIZSET,CCUGPROF,COSTT4_A,...,OPENADMP_3.0,OPEFLAG_0.0,OPEFLAG_1.0,OPEFLAG_2.0,OPEFLAG_3.0,OPEFLAG_5.0,OPEFLAG_7.0,OPEFLAG_8.0,Year,MD_EARN_WNE_P6
0,-1.686152,-2.467388,-1.123197,-0.580916,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,28400.000000
1,0.903349,-1.216280,-0.640738,0.389326,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,34300.000000
2,0.017765,4.234976,2.393439,-1.665272,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,29471.207226
3,1.413031,-1.126915,-0.496052,0.123803,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,37400.000000
4,-1.264421,-2.646118,-1.182215,-0.566444,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,24000.000000

In [29]:
# selcting specific columns

complete_df.iloc[:, :].head()

,ADM_RATE,AGEGE24,AGE_ENTRY,AVGFACSAL,C150_4_POOLED_SUPP,C150_L4_POOLED_SUPP,CCBASIC,CCSIZSET,CCUGPROF,COSTT4_A,...,OPENADMP_3.0,OPEFLAG_0.0,OPEFLAG_1.0,OPEFLAG_2.0,OPEFLAG_3.0,OPEFLAG_5.0,OPEFLAG_7.0,OPEFLAG_8.0,Year,MD_EARN_WNE_P6
0,-1.686152,-2.467388,-1.123197,-0.580916,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,28400.000000
1,0.903349,-1.216280,-0.640738,0.389326,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,34300.000000
2,0.017765,4.234976,2.393439,-1.665272,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,29471.207226
3,1.413031,-1.126915,-0.496052,0.123803,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,37400.000000
4,-1.264421,-2.646118,-1.182215,-0.566444,1.0,-1.0,0.0,1.0,0.0,0.038178,...,0,1,0,0,0,0,0,0,2003,24000.000000

In [32]:
zero_df = [
    'C150_4_POOLED_SUPP',
    'C150_L4_POOLED_SUPP',
    'CCBASIC',
    'CCSIZSET',
    'CCUGPROF',
    'RELAFFIL',
    'UG'
    
]

In [33]:
complete_df.drop(zero_df, axis=1, inplace=True)

In [34]:
complete_df

,ADM_RATE,AGEGE24,AGE_ENTRY,AVGFACSAL,COSTT4_A,COSTT4_P,D150_4_AIANOLD,D150_4_HISPOLD,D150_L4_AIANOLD,D150_L4_HISPOLD,...,OPENADMP_3.0,OPEFLAG_0.0,OPEFLAG_1.0,OPEFLAG_2.0,OPEFLAG_3.0,OPEFLAG_5.0,OPEFLAG_7.0,OPEFLAG_8.0,Year,MD_EARN_WNE_P6
0,-1.686152,-2.467388,-1.123197,-0.580916,0.038178,0.040647,-0.502342,-0.590263,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,28400.000000
1,0.903349,-1.216280,-0.640738,0.389326,0.038178,0.040647,0.222784,-0.536211,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,34300.000000
2,0.017765,4.234976,2.393439,-1.665272,0.038178,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,29471.207226
3,1.413031,-1.126915,-0.496052,0.123803,0.038178,0.040647,-0.018925,-0.557832,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,37400.000000
4,-1.264421,-2.646118,-1.182215,-0.566444,0.038178,0.040647,-0.623197,-0.601073,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,24000.000000
5,1.351033,-2.556753,-1.126975,0.287459,0.038178,0.040647,2.398161,-0.395678,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,36000.000000
6,0.017765,0.481652,0.199160,-1.023454,0.038178,0.040647,-0.006448,-0.012273,-0.492593,-0.847698,...,0,1,0,0,0,0,0,0,2003,23200.000000
7,0.017765,1.464666,1.067482,0.068138,0.038178,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,1,1,0,0,0,0,0,0,2003,36100.000000
8,2.250006,-0.948185,-0.452449,-0.181798,0.038178,0.040647,-0.502342,-0.568642,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,29800.000000
9,0.695007,-3.003577,-1.348473,0.621449,0.038178,0.040647,1.552181,-0.438919,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,39700.000000
10,1.482239,-3.361036,-1.579853,0.042532,0.038178,0.040647,-0.381488,-0.601073,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,39000.000000
11,0.017765,1.375301,0.513241,-0.672207,0.038178,0.040647,-0.006448,-0.012273,-0.759524,-0.686499,...,0,1,0,0,0,0,0,0,2003,24000.000000
12,0.017765,0.749747,0.922818,-0.799680,0.038178,0.040647,-0.623197,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,19300.000000
13,2.309841,2.090220,0.855011,-1.644119,0.038178,0.040647,-0.623197,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,27700.000000
14,0.017765,0.660382,0.327969,-0.742345,0.038178,0.040647,-0.006448,-0.012273,0.041271,-0.668588,...,0,1,0,0,0,0,0,0,2003,21300.000000
15,0.017765,-0.322631,-0.186436,-0.678887,0.038178,0.040647,-0.006448,-0.012273,-0.092195,-0.811876,...,0,1,0,0,0,0,0,0,2003,22600.000000
16,-0.916943,2.179584,0.961453,-0.991168,0.038178,0.040647,-0.623197,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,31300.000000
17,0.017765,0.928477,0.451447,-0.715069,0.038178,0.040647,-0.006448,-0.012273,0.174737,-0.722321,...,0,1,0,0,0,0,0,0,2003,23500.000000
18,0.017765,0.660382,0.315884,-0.780754,0.038178,0.040647,-0.006448,-0.012273,-0.225661,-0.722321,...,0,1,0,0,0,0,0,0,2003,21800.000000
19,0.017765,0.392287,0.362613,-0.874271,0.038178,0.040647,-0.006448,-0.012273,-0.492593,-0.829787,...,0,1,0,0,0,0,0,0,2003,23600.000000
20,0.017765,-0.054537,0.029313,-0.945523,0.038178,0.040647,-0.006448,-0.012273,-0.759524,-0.847698,...,0,1,0,0,0,0,0,0,2003,19800.000000
21,-0.583163,2.000855,0.615991,-1.386390,0.038178,0.040647,-0.623197,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,30100.000000
22,-0.683369,-2.109928,-0.908865,-0.604852,0.038178,0.040647,-0.502342,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,32500.000000
23,0.017765,2.626409,1.636095,-1.425912,0.038178,0.040647,-0.623197,-0.622693,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,24400.000000
24,0.017765,2.090220,0.914162,-0.928267,0.038178,0.040647,-0.006448,-0.012273,-0.092195,-0.847698,...,0,1,0,0,0,0,0,0,2003,20200.000000
25,1.533423,-1.216280,-0.478881,-0.326527,0.038178,0.040647,0.222784,-0.536211,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,32400.000000
26,0.017765,0.392287,0.196459,-0.648828,0.038178,0.040647,-0.006448,-0.012273,-0.626058,-0.811876,...,0,1,0,0,0,0,0,0,2003,22200.000000
27,0.017765,0.571017,0.184433,-0.713956,0.038178,0.040647,-0.006448,-0.012273,-0.626058,-0.793965,...,0,1,0,0,0,0,0,0,2003,27600.000000
28,0.017765,0.839112,0.269652,-0.599286,0.038178,0.040647,-0.006448,-0.012273,3.511384,-0.722321,...,0,1,0,0,0,0,0,0,2003,23700.000000
29,0.740424,-1.663104,-0.756798,-0.985602,0.038178,0.040647,-0.502342,-0.611883,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2003,24500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33826,0.017765,-0.004101,1.117356,-1.508297,-0.346056,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,19700.000000
33827,0.017765,-0.004101,1.117356,-1.455971,-0.314456,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,19700.000000
33828,0.017765,-0.004101,-0.386439,-0.112121,0.038178,-0.268523,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29200.000000
33829,0.017765,-0.004101,0.375145,-0.222433,-1.190327,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,24400.000000
33830,0.017765,-0.004101,0.561718,-0.112121,0.038178,-3.135288,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,26400.000000
33831,0.017765,-0.004101,-0.534797,-0.585926,-1.543424,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,27500.000000
33832,0.017765,-0.004101,0.538220,-0.052655,-1.312606,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29471.207226
33833,0.017765,-0.004101,-0.133838,-0.112121,0.038178,5.917912,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,15100.000000
33834,0.017765,-0.004101,1.152936,-0.157862,-1.512740,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29471.207226
33835,0.017765,-0.004101,-0.635149,-0.112121,0.038178,-2.973427,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29471.207226
33836,0.017765,-0.004101,0.529801,-0.112121,0.038178,-1.017416,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29471.207226
33837,0.017765,-0.004101,0.916482,-2.715115,0.051693,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,23900.000000
33838,0.017765,-0.004101,3.053065,-0.112121,0.038178,-2.528879,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,29471.207226
33839,0.017765,-0.004101,-0.154630,-0.112121,0.038178,-0.014713,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,16800.000000
33840,0.017765,-0.004101,1.067455,-1.735410,0.604465,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,23300.000000
33841,0.400156,-0.004101,-1.141398,-0.932720,3.043165,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,23400.000000
33842,0.017765,-0.004101,0.465364,-0.343783,0.071385,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,20900.000000
33843,0.017765,-0.004101,0.309037,-0.112121,0.038178,-3.703701,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,14100.000000
33844,0.017765,-0.004101,2.174306,-0.112121,0.038178,-1.524656,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,15500.000000
33845,0.017765,-0.004101,0.416266,-0.112121,0.038178,-2.531158,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,16900.000000
33846,0.017765,-0.004101,0.924681,-0.127246,-1.404658,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,24300.000000
33847,0.017765,-0.004101,1.095602,-0.112121,0.654842,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,26100.000000
33848,0.017765,-0.004101,1.249591,-0.333764,0.530273,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,20500.000000
33849,0.017765,-0.004101,0.555698,-0.112121,0.038178,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,70900.000000
33850,0.017765,-0.004101,0.632164,-0.112121,0.038178,-3.628090,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,13600.000000
33851,0.017765,-0.004101,0.342854,-0.112121,0.038178,-1.270846,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,12500.000000
33852,0.017765,-0.004101,1.020440,-1.612390,0.038178,2.924243,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,18100.000000
33853,-0.470701,-0.004101,1.458392,-0.705050,0.397232,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,26100.000000
33854,0.017765,-0.004101,0.816000,-0.299808,-1.529570,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,21500.000000
33855,0.017765,-0.004101,0.931211,-0.691690,0.659536,0.040647,-0.006448,-0.012273,-0.003411,-0.011883,...,0,1,0,0,0,0,0,0,2014,25800.000000

In [23]:
target = 'MD_EARN_WNE_P6'
train, test = model.sampling_data(df)
x_train, y_train, x_test, y_test = model.split_data(train, test, target)